# Generated by Django 5.2.10 on 2026-01-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
